doSomethingAsync()
  .then((result) => {
    // If the operation was successful, we end up here
  })
  .catch((err) => {
    // If the operation failed, we end up here
  });
